name: grocery_store
description: A new Flutter project.
version: 1.1.7+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  cloud_firestore: ^3.1.6
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  #flushbar: ^1.10.4
  another_flushbar: ^1.10.28
  flutter_bloc: ^7.3.3
  flutter_local_notifications: ^9.2.0
  flutter_share: ^2.0.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  http: ^0.13.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  smooth_star_rating: ^1.1.1
  uuid: ^3.0.5
  flutter_credit_card: ^3.0.1
  intl_phone_field: ^3.0.1
  intl_phone_number_input: ^0.7.0+2
  paginate_firestore: ^1.0.3
  cached_network_image: ^3.2.0
  webview_flutter: ^3.0.0
  day_picker: ^2.1.0
  flutter_native_image: ^0.0.6
  url_launcher: ^6.0.18
  permission_handler: ^8.3.0
  stop_watch_timer: ^1.3.1
  readmore: ^2.1.0
  twilio_voice:
    git:
      url: https://github.com/Git-focalpoint/jerasTwilioVoiceCalling.git
      ref: master
  cloud_functions: ^3.2.5
  flutter_sound:
  assets_audio_player: ^3.0.3+9
  package_info_plus: ^1.3.0
  sms_autofill: ^2.2.0
  country_picker: ^2.0.10
  open_file: ^3.2.1
  pdf: ^3.6.5
  open_document: ^1.0.3
  shimmer: ^2.0.0
  linkwell: ^2.0.6
  flutter_smartlook: ^3.0.5
  firebase_phone_auth_handler: ^0.0.8
  firebase_crashlytics: ^2.4.5
  auto_direction: ^0.0.5
  agora_uikit: ^0.0.4
  agora_rtc_engine: ^4.2.2
  rating_dialog: ^2.0.1
  store_redirect:
  wakelock: ^0.6.1+1
  pip_view: ^0.9.5
  group_radio_button: ^1.2.0
  youtube_player_flutter: ^8.0.0
  hijri_picker: ^3.0.0








dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/OpenSans-Regular.ttf
    - assets/images/
    - assets/applicationIcons/
    - assets/icons/
    - assets/banners/
    - lib/lang/arJeras.json
    - lib/lang/enJeras.json
    - lib/lang/fr.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf


    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf